name = "workers-sh-dev"
type = "webpack"
webpack_config = "./packages/worker/webpack.config.js"
account_id = "5a883b414d4090a1442b20361f3c43a9"
workers_dev = true

kv-namespaces = [
	{ binding = "CLOUDFLARE", id = "ff9370e10a69405ea56f1bceba2e7088" },
	{ binding = "TAIL", id = "19d44665244140b39fe3de4370e2287d" }
]

[site]
bucket = "./packages/client/build"
entry-point = "./packages/worker"

[env.production]
name = "workers-sh"
zone_id = "87d33ac29978760c33716c525858644f"
routes = [ "workers.sh/*", "www.workers.sh/*" ]

kv-namespaces = [
	{ binding = "CLOUDFLARE", id = "ff9370e10a69405ea56f1bceba2e7088" },
	{ binding = "TAIL", id = "19d44665244140b39fe3de4370e2287d" }
]