# name: Deploy
# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     name: Deploy
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Setup Node
#         uses: actions/setup-node@v1
#         with:
#           fetch-depth: 1
#       - name: Install
#         run: npm ci
#         env:
#           GITHUB_TOKEN: ${{ github.token }}
#       - name: Deploy
#         run: npm run deploy
#         env:
#           CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
